CREATE TABLE IF NOT EXISTS student_suggestions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    content_id INT NULL,
    converted_content_id INT NULL,
    title VARCHAR(200) NOT NULL,
    url VARCHAR(500) NOT NULL,
    audience VARCHAR(200) NOT NULL,
    learning_outcome TEXT NOT NULL,
    recommendation_reason TEXT NOT NULL,
    critical_check TEXT NOT NULL,
    share_with_students BOOLEAN NOT NULL DEFAULT FALSE,
    display_first_name BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'submitted',
    reviewer_id INT NULL,
    reviewer_note TEXT NULL,
    display_title VARCHAR(200) NULL,
    display_summary TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP NULL,
    INDEX idx_student_suggestions_student (student_id),
    INDEX idx_student_suggestions_status (status),
    INDEX idx_student_suggestions_reviewer (reviewer_id),
    INDEX idx_student_suggestions_content (content_id),
    INDEX idx_student_suggestions_converted_content (converted_content_id),
    CONSTRAINT fk_student_suggestions_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_student_suggestions_content FOREIGN KEY (content_id) REFERENCES content(id) ON DELETE SET NULL,
    CONSTRAINT fk_student_suggestions_converted_content FOREIGN KEY (converted_content_id) REFERENCES content(id) ON DELETE SET NULL,
    CONSTRAINT fk_student_suggestions_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
